import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SignupNavbar } from "@/components/Signup/SignupNavbar";
import { Footer } from "@/components/Footer";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/components/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zolush's Food Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <SignupNavbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
